version: '2'
networks:
  pharmanexo-network:
    external: true
services:
  pharmanexo_app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: pharmanexo
    container_name: pharmanexo-web
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - pharmanexo-network
  pharmanexo_nginx:
    image: nginx:1.17-alpine
    container_name: pharmanexo-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - pharmanexo-network
  pharmanexo_db:
    image: mysql/mysql-server:8.0.23
    container_name: pharmanexo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - pharmanexo-network
    ports:
      - 3306:3306