<!DOCTYPE html>
<html lang="pt-BR">
<?php if (isset($header)) echo $header; ?>
<body class="bg-light">
<?php if (isset($navbar)) echo $navbar; ?>
<?php if (isset($sidebar)) echo $sidebar; ?>
<div class="container py-3 mb-3 text-justify">
    <h3 class="titulo titulo-primary titulo-lg mb-3">Termos de Uso</h3>
    <p class="PARAGRAPH-TITLES" id="u59559-2">Aos usuários da Plataforma Pharmanexo</p>
    <p class="PARAGRAPH-TITLES" id="u59559-3">&nbsp;</p>
    <p id="u59559-5">Obrigado por dedicar este tempo para ler o Sumário do contrato com a Pharmanexo.</p>

    <p id="u59559-8">As informações ora transmitidas ajudarão os interessados a operar nossa plataforma de anúncios.</p>

    <p id="u59559-11">É de extrema importância que as nossas políticas sejam conhecidas e, por esta razão, é necessário que se leia e compreenda os Termos e Condições Gerais de Uso do Site, bem como que se compreendam as cláusulas que viabilizam a contratação dos serviços da Plataforma e as cláusulas limitativas de direitos, abaixo destacadas:</p>

    <p id="u59559-14">A Pharmanexo não é fornecedora de quaisquer produtos ou serviços anunciados no site.</p>

    <p id="u59559-17">A Pharmanexo é uma prestadora de serviços, os quais consistem na oferta de uma plataforma na internet que fornece espaços para que Usuários anunciantes - potenciais vendedores anunciem, oferecendo à venda os seus próprios produtos e serviços para que eventuais interessados na aquisição dos mesmos, os Usuários - potenciais compradores, possam negociar direta e exclusivamente entre si;</p>

    <p id="u59559-20">Os Usuários anunciantes - potenciais vendedores somente poderão anunciar produtos ou serviços que possam vender e que tenham em estoque, estabelecendo diretamente os termos do anúncio e todas as suas características (como título, descrição e imagem dos bens, preço, categoria, quantidade, condições de venda, forma e prazo de entrega, além da forma de pagamento);</p>

    <p id="u59559-23">Para utilizar os serviços da Pharmanexo os Usuários devem aceitar, expressamente, a Política de Privacidade e Confidencialidade de Informação, que contém informações claras e completas sobre coleta, uso, armazenamento, tratamento e proteção dos dados pessoais dos Usuários e visitantes da Pharmanexo.</p>
    <p id="u59559-26">Os Usuários deverão efetuar um cadastro único, criando um apelido (login) e senha, que são pessoais e intransferíveis.</p>
    <p id="u59559-29">A Pharmanexo não se responsabiliza pelo uso inadequado e divulgação dos citados dados para terceiros.</p>
    <p id="u59559-32">A Pharmanexo, nem quaisquer de seus empregados ou prepostos solicitará, por qualquer meio, físico ou eletrônico, que sejam informados o login e a senha de quaisquer usuários;</p>
    <p id="u59559-35">Em razão de violação à legislação em vigor ou aos Termos e Condições Gerais de Uso do Site, a Pharmanexo, conforme a situação, poderá, sem prejuízo de outras medidas, recusar qualquer solicitação de cadastro, advertir, suspender, temporária ou definitivamente, a conta de um Usuário e seus anúncios.</p>
    <p id="u59559-38"><span id="u59559-37">Não é permitido anunciar produtos expressamente proibidos pela legislação vigente ou pelos Termos e Condições Gerais de Uso do Site, que não possuam a devida autorização específica de órgãos reguladores competentes, ou que violem direitos de terceiros;</span></p>
    <p id="u59559-41">O Usuário - potencial comprador, antes de decidir pela compra, deverá atentar-se às informações sobre o preço, às formas de pagamento, à disponibilidade, à forma e ao prazo de entrega dos produtos e serviços e as disposições do Código Civil e Código de Defesa do Consumidor.</p>
    <p id="u59559-45">Termos e Condições Gerais de Uso do Site</p>
    <p id="u59559-48">Estes Termos e Condições Gerais aplicam-se ao uso dos serviços oferecidos pela&nbsp; PHARMANEXO INTERMEDIAÇÃO DE NEGÓCIOS, situada na Av. Nossa Senhora dos Navegantes, n. 955, Sala 719, Enseada do Suá, Vitória-ES, Cep. 29.050-335, doravante nominada simplesmente de Pharmanexo, por meio do site pharmanexo.com.br.</p>
    <p id="u59559-51">Qualquer pessoa jurídica, doravante nominada Usuário(a), que pretenda utilizar os serviços da Pharmanexo deverá aceitar os Termos e Condições Gerais de Uso do Site, bem como todas as demais políticas e princípios que o regem.</p>
    <p id="u59559-54"><span id="u59559-53">A aceitação destes Termos e condições gerais é absolutamente indispensável à utilização do site e dos serviços prestados pela Pharmanexo.</span></p>
    <p id="u59559-57"><span id="u59559-56">O Usuário deverá ler e certificar-se de haver entendido todas as condições estabelecidas nos Termos e Condições Gerais do Uso do Site e nas Políticas de Privacidade, assim como nos demais documentos a eles incorporados por referência, antes de seu cadastro como Usuário da Pharmanexo.</span></p>
    <p id="u59559-60">Em caso de dúvidas, acesse Contato ou SAC ou Chat on Line.</p>
    <p id="u59559-64">01 - Objeto</p>
    <p id="u59559-67">Os serviços objeto dos presentes Termos e condições gerais consistem em (i) ofertar e hospedar espaços nos Sites para que os Usuários anunciem à venda seus próprios produtos e/ou serviços e (ii) viabilizar o contato entre Usuários vendedores e Usuários interessados em adquirir os produtos e serviços anunciados.</p>
    <p id="u59559-70">A Pharmanexo, logo, possibilita aos Usuários negociarem entre si, sem qualquer intervenção da Pharmanexo, na negociação ou na concretização dos negócios.</p>
    <p id="u59559-73">Portanto, enfatiza-se que a Pharmanexo não fornece quaisquer produtos ou serviços anunciados pelos Usuários – potenciais vendedores ou compradores no Site.</p>
    <p id="u59559-77">02 - Capacidade para cadastrar-se</p>
    <p id="u59559-80">Os serviços da Pharmanexo estão disponíveis apenas para as jurídicas que tenham capacidade legal para contratá-los.</p>
    <p id="u59559-83">É proibido o cadastro de Usuários que não sejam pessoas jurídicas habilitadas à aquisição e comércio de medicamentos e insumos, bem como de Usuários que tenham sido suspensos da Pharmanexo, temporária ou definitivamente, sem prejuízo da aplicação das sanções legais previstas no Código Civil Brasileiro, notadamente, art. 166, inciso I; art. 171, inciso I e art. 180.</p>
    <p id="u59559-86"><span id="u59559-85">Inabilitação e suspensão de usuários</span></p>
    <p id="u59559-90">03 - Cadastro</p>
    <p id="u59559-93">O cadastramento do Usuário somente será permitido àquele que preencher todos os campos obrigatórios do cadastro, com informações exatas, precisas e verdadeiras.</p>
    <p id="u59559-96">O Usuário declara e assume o compromisso de atualizar os dados inseridos em seu cadastro sempre que for necessário.</p>
    <p id="u59559-99">Ao se cadastrar na plataforma Pharmanexo, o Usuário poderá utilizar-se dos serviços de pagamento e logística disponibilizados/intermediados pela Pharmanexo.</p>
    <p id="u59559-102">Para tanto, os Usuários serão condicionados à declaração de ter lido, compreendido e aceitado os respectivos Termos e Condições de uso de cada serviço, os quais passam a fazer parte integrante destes Termos e Condições Gerais, após a conclusão do cadastro.</p>
    <p id="u59559-105">Os Usuários acessarão sua conta através de e-mail ou apelido (login) e senha e comprometem-se a não informar a terceiros esses dados, responsabilizando-se integralmente pelo mal uso que deles seja feito.</p>
    <p id="u59559-108">A Pharmanexo não se responsabiliza pela correção dos Dados Pessoais inseridos por seus Usuários.</p>
    <p id="u59559-111">Os Usuários garantem e respondem, em qualquer caso, civil e criminalmente pela veracidade, exatidão e autenticidade, dos Dados Pessoais cadastrados.</p>
    <p id="u59559-114">O apelido que o Usuário utilizará na Pharmanexo não poderá guardar semelhança com o nome Pharmanexo, suas marcas e nomes de domínio, ou outro bem de propriedade intelectual da referida empresa.</p>
    <p id="u59559-117">Tampouco poderá ser utilizado qualquer apelido que insinue ou sugira que os produtos/serviços anunciados pertencem ou tenham qualquer relação com a Pharmanexo.</p>
    <p id="u59559-120">Também serão excluídos apelidos considerados ofensivos, bem como os que contenham Dados Pessoais do Usuário ou alguma URL ou endereço eletrônico.</p>
    <p id="u59559-123">O Pharmanexo se reserva o direito de recusar qualquer solicitação de cadastro e de suspender um cadastro previamente aceito, que esteja em desacordo com as políticas e regras dos presentes Termos e Condições Gerais.</p>
    <p id="u59559-126">O Pharmanexo poderá, a seu exclusivo critério, realizar as buscas que julgar necessárias para apurar dados incorretos ou inverídicos bem como solicitar dados adicionais e documentos que estime serem pertinentes a fim de conferir os Dados Pessoais informados.</p>
    <p id="u59559-129">Caso se constate haver dados incorretos ou inverídicos no cadastro dos Usuários, ou ainda, caso o Usuários se furtem ou se neguem a enviar os documentos requeridos, a Pharmanexo poderá suspender temporariamente ou definitivamente a respectiva conta, sem prejuízo de outras medidas que entender necessárias e oportunas.</p>
    <p id="u59559-132">Havendo a aplicação de quaisquer das sanções acima referidas, automaticamente serão cancelados os anúncios do respectivo Usuário, não lhe assistindo, por essa razão, qualquer indenização ou ressarcimento.</p>
    <p id="u59559-135">O Usuário compromete-se a notificar a Pharmanexo imediatamente, por meio seguro e eficaz, a respeito de qualquer uso não autorizado de sua conta, bem como seu acesso não autorizado por terceiros.</p>
    <p id="u59559-138">O Usuário será o único responsável pelas operações efetuadas em sua conta, uma vez que o acesso só será possível mediante a inclusão da senha, que deverá ser de conhecimento e propriedade exclusiva.</p>
    <p id="u59559-141">Em nenhuma hipótese será permitida a cessão, venda, aluguel ou outra forma de transferência da conta.</p>
    <p id="u59559-144">Também não se permitirá a manutenção de mais de um cadastro por uma mesma pessoa jurídica (mesmo CNPJ), ou ainda a criação de novos cadastros por pessoas cujos cadastros originais tenham sido suspensos temporária ou definitivamente por infrações às políticas da Pharmanexo.</p>
    <p id="u59559-148">04 - Modificações dos Termos e condições gerais</p>
    <p id="u59559-151">A Pharmanexo poderá alterar, a qualquer tempo, estes Termos e condições gerais, visando seu aprimoramento e melhoria dos serviços prestados.</p>
    <p id="u59559-154">Os novos Termos e condições gerais entrarão em vigor 10 (dez) dias após sua publicação no Site.</p>
    <p id="u59559-159">No prazo de 05 (cinco) dias, contados a partir da publicação da nova versão, o Usuário deverá <span id="u59559-157">comunicar-se por e-mail</span> caso não concorde com os termos alterados. Nesse caso, o vínculo contratual deixará de existir, desde que não haja contas ou dívidas em aberto.</p>
    <p id="u59559-162">Não havendo manifestação no prazo estipulado, entender-se-á que o Usuário aceitou os novos Termos e condições gerais de uso e o contrato continuará vinculando as partes.</p>
    <p id="u59559-165">As alterações não vigorarão em relação às negociações e anúncios já iniciados antes de sua publicação, permanecendo, nestes casos, vigente a redação anterior.</p>
    <p id="u59559-169">05 - Produtos anunciados</p>
    <p id="u59559-172">5.1 Anúncios/ofertas</p>
    <p id="u59559-175">O Usuário poderá anunciar a venda de medicamentos ou insumos, desde que possuidor das devidas autorizações, licenças e permissões dos órgãos competentes.</p>
    <p id="u59559-178">Os anúncios deverão conter as informações comerciais e técnicas necessárias à devida compreensão do negócio jurídico a ser concretizado.</p>
    <p id="u59559-181">Em caso de dúvidas, a Pharmanexo disponibiliza os canais de&nbsp; Contato, SAC ou Chat on Line, para maiores esclarecimentos.</p>
    <p id="u59559-184">O produto ou serviço oferecido pelo Usuário vendedor deve ser descrito com clareza, contendo todas as características relevantes.</p>
    <p id="u59559-187">Diante da inclusão do anúncio no site da Pharmanexo, o Usuário manifesta a intenção e declara possuir o direito de vender o produto anunciado, além de dispor do produto em estoque para entrega imediata.</p>
    <p id="u59559-190">A Pharmanexo poderá remover aqueles anúncios cujo preço final não esteja de acordo com os Termos e condições gerais de uso e suas políticas, não seja suficientemente claro, ou que permita algum tipo de dúvida ou variação sobre o preço, para evitar qualquer mal entendido ou indução em erro quanto ao preço final do produto.</p>
    <p id="u59559-193">O Usuário deve inserir a quantidade de produtos que deseja vender e o preço por unidade.</p>
    <p id="u59559-196">Se possuir várias unidades de um mesmo produto que não quer ou não possa vender separadamente, ou seja, um conjunto, o usuário vendedor deve inserir o preço do conjunto, estando ciente de que a tarifa de venda será cobrada pelo valor do conjunto anunciado, ainda que o usuário decida vender, posteriormente à publicação do anúncio, uma ou mais unidades, de forma isolada.</p>
    <p id="u59559-199">Tendo em vista que o usuário comprador recebe os dados de contato do Usuário anunciante (e vice-versa) após manifestar a intenção na compra do produto anunciado, não é permitido inserir ou manter no próprio anúncio quaisquer dados pessoais para contato, tais como, e sem se limitar, a números de telefones, endereços de e-mails, ou páginas de internet que contenham os dados mencionados anteriormente.</p>
    <p id="u59559-202">Não é permitido fazer publicidade de outros meios de pagamentos que não sejam expressamente disponibilizados no Site.</p>
    <p id="u59559-208">5.1.2 Processamento de pagamento</p>
    <p id="u59559-211">O usuário declara e reconhece que o processamento de pagamentos depende do cumprimento de alguns procedimentos, como análise de risco e compensação bancária, a depender do meio utilizado e das formas e condições estabelecidas pelo anunciante vendedor.</p>
    <p id="u59559-214">Em regra, os pagamentos por cartão de crédito ou dinheiro via gateway de pagamento disponibilizado pela Pharmanexo, são processados de forma mais rápida do que pagamentos realizados por boleto bancário.</p>
    <p id="u59559-217">Assim, a Pharmanexo não poderá ser responsável por eventuais descumprimentos de ofertas feitas pelo usuário vendedor quando o processamento de pagamento ocorrer depois de esgotado o estoque do produto anunciado, lembrando que a efetivação da negociação dependerá de prévia confirmação pela Pharamexo.</p>
    <p id="u59559-221">5.2 Inclusão de imagens, fotografias e vídeos</p>
    <p id="u59559-224">O usuário poderá incluir imagens, fotografias e vídeos do produto oferecido sempre que estas correspondam exatamente ao produto anunciado.</p>
    <p id="u59559-227">A Pharmanexo poderá retirar dos Sites anúncios que contenham imagens, fotografias ou vídeos que não estejam de acordo com os Termos e Condições Gerais de Uso e demais políticas de utilização do Site.</p>
    <p id="u59559-231">5.3 Produtos Proibidos</p>
    <p id="u59559-234">Poderão ser anunciados/ofertados aqueles produtos (medicamentos e insumos) cuja venda não esteja expressamente proibida pelos Termos e Condições Gerais, demais políticas da Pharmanexo, ou pela lei vigente.</p>
    <p id="u59559-238">06 - Privacidade da Informação</p>
    <p id="u59559-241">Toda informação ou Dado Pessoal do Usuário é armazenado em servidores ou meios magnéticos de alta segurança.</p>
    <p id="u59559-244">Salvo com relação às informações que são publicadas no Site, a Pharmanexo adotará todas as medidas possíveis para manter a confidencialidade e a segurança das informações sigilosas, porém não se responsabilizará por eventuais prejuízos que sejam decorrentes da divulgação de tais informações por parte de terceiros que utilizem as redes públicas ou a internet, subvertendo os sistemas de segurança para acessar as informações de Usuários.</p>
    <p id="u59559-247">Em caso de dúvidas sobre a proteção a Dados Pessoais ou para obter mais informações sobre Dados Pessoais e os casos nos quais poderá ser quebrado o sigilo de que trata esta cláusula, por favor, consultar as políticas de Privacidade e Confidencialidade da Pharmanexo.</p>
    <p id="u59559-251">07 - Obrigações dos Usuários</p>
    <p id="u59559-254">7.1 Obrigações do Usuário comprador/adquirente.</p>
    <p id="u59559-257">Os usuários interessados em comprar os produtos anunciados por vendedores no site Pharmanexo devem manifestar seu interesse durante o período de vigência estipulado no anúncio.</p>
    <p id="u59559-260">Os anúncios tem duração correspondente ao tipo de anúncio e categoria escolhidos pelo Usuário vendedor encerrando-se quando expirado o respectivo prazo de duração ou quando acabar a quantidade do produto anunciado.</p>
    <p id="u59559-263">O Usuário comprador, após manifestar interesse na compra de um item anunciado por meio das ferramentas do Site, obriga-se a aguardar o contato da Pharmanexo, por qualquer meio, para confirmação da efetivação do negócio pactuado, salvo se a negociação for proibida por lei ou por estes Termos e Condições Gerais de Uso.</p>
    <p id="u59559-266">Ao manifestar o interesse em algum produto, o Usuário comprador obriga-se a atender às condições de venda descritas no anúncio. As ofertas só terão validade se realizadas no site da Pharmanexo.</p>
    <p id="u59559-269"><span id="u59559-268">Tributos: O Pharmanexo não se responsabiliza pelas obrigações tributárias que recaiam sobre as atividades dos Usuários dos Sites. Assim como estabelece a legislação pertinente em vigor, o Usuário comprador deverá exigir nota fiscal do Usuário vendedor em suas negociações.</span></p>
    <p id="u59559-273">7.2. Obrigações do Usuário vendedor/anunciante</p>
    <p id="u59559-276">O Usuário vendedor, pessoa jurídica, deve ter capacidade legal e as devidas autorizações exigidas pela legislação em vigor, para vender os produtos anunciados – medicamentos ou insumos.</p>
    <p id="u59559-279"><span id="u59559-278">Apenas nos seguintes casos excepcionais, o Usuário vendedor poderá não efetivar a venda: se não houve acordo com o Usuário comprador sobre a forma de pagamento ou prazo de entrega; se não foi possível verificar a verdadeira identidade ou as informações do Usuário comprador; ou se houve evidente erro de digitação ao cadastrar preço ou quantidade do produto anunciado.</span></p>
    <p id="u59559-282">O Usuário vendedor deve, em cumprimento à legislação brasileira vigente, além de demonstrar informações claras e ostensivas a respeito de quaisquer restrições à aquisição do produto ou serviço, apontar sempre em seus anúncios as características essenciais dos produtos, incluídos os riscos à saúde e à segurança dos consumidores.</p>
    <p id="u59559-285">Deve ser igualmente apontado pelo Usuário vendedor no anúncio quaisquer despesas adicionais que devam ser pagas pelo Usuário comprador para aquisição do produto ou serviço, tais como despesas de entrega ou seguros.</p>
    <p id="u59559-288">Também deverá ser apontada, por todos os Usuários vendedores, a aplicação do Código Civil e Código de Defesa do Consumidor sempre que possível nas negociações em questão.</p>
    <p id="u59559-291">Todos os Usuários vendedores deverão, obrigatoriamente, disponibilizar aos usuários compradores a opção da utilização do gateway de pagamento disponibilizado pela Pharmanexo, que permite o gerenciamento e a efetivação de pagamentos por diversos meios, tais como cartão de crédito, boleto bancário.</p>
    <p id="u59559-294">A Pharmanexo reserva-se ao direito de requerer, de acordo com os critérios que estime pertinentes, que determinados produtos, bem como Usuários vendedores somente anunciem seus bens no Site mediante a utilização do gateway de pagamento e/ou outras ferramentas disponibilizadas pela Pharmanexo para cobrança do bem vendido.</p>
    <p id="u59559-297">Quando uma negociação se concretizar, o Usuário vendedor deverá, sempre que e conforme previsto, pagar ao Pharmanexo, em contrapartida aos serviços descritos na cláusula 1, o valor correspondente a um percentual do preço anunciado.</p>
    <p id="u59559-300"><span id="u59559-299">Em virtude de a Pharmanexo não figurar como parte nas negociações de compra e venda de serviços e produtos que se realizam entre os Usuários, a responsabilidade por todas as obrigações decorrentes, sejam fiscais, trabalhistas, consumeristas ou de qualquer outra natureza, será exclusivamente do Usuário vendedor.</span></p>
    <p id="u59559-303">Assim, o Usuário vendedor declara e reconhece que na hipótese de a Pharmanexo vir a ser demandada judicialmente ou tenha contra ela uma reclamação dos órgãos de proteção ao consumidor ou demais órgãos quaisquer, os valores relativos às condenações, acordos, despesas processuais e honorários advocatícios, dispendidos pela empresa serão de responsabilidade do Usuário vendedor que deu causa, autorizando.</p>
    <p id="u59559-306">Por não figurar como parte nas negociações de compra e venda que se realizam entre os Usuários, a Pharmanexo também não pode obrigar o Usuário vendedor a honrar sua obrigação ou efetivar a negociação.</p>
    <p id="u59559-309">Por razões de segurança, a conta do Usuário vendedor, poderá ser suspensa, a critério do Pharmanexo, caso este suspeite de qualquer ilegitimidade, fraude ou qualquer outro ato contrário às disposições dos presentes Termos e Condições Gerais de Uso ou ainda até a apuração e verificação de (i) questões relativas à idoneidade do Usuário; (ii) legalidade das negociações realizadas; (iii) reclamações pendentes; (iv) excesso de reclamações.</p>
    <p id="u59559-312"><span id="u59559-311">Tributos: A Pharmanexo não se responsabiliza pelas obrigações de natureza tributária que incidam sobre os negócios realizados entre Usuário comprador e Usuário vendedor. Assim, o Usuário vendedor que atue de forma contínua, nos termos da lei em vigor, responsabilizar-se-á pela integralidade das obrigações oriundas de suas atividades, notadamente pelos tributos incidentes.</span></p>
    <p id="u59559-316">08 - Práticas vedadas</p>
    <p id="u59559-319">Os Usuários não poderão, entre outras atitudes previstas nestes Termos e condições gerais e seus anexos: a) manipular os preços dos produtos anunciados; b) interferir nas negociações entre outros Usuários; c) manter algum tipo de comunicação direta, por e-mail ou por qualquer outra forma, salvo através da sessão de perguntas e respostas dos Sites, com Usuário que potencialmente seja a sua contraparte em uma negociação, antes de manifestada a intenção na compra do respectivo item; d) divulgar dados pessoais de contato por qualquer meio, em qualquer espaço do Site; e) anunciar produtos proibidos pelas políticas da Pharmanexo e pela legislação; f) agredir, caluniar, injuriar ou difamar outros Usuários; g) adicionar em seus anúncios acréscimos de preço caso o comprador opte por realizar o pagamento pelo gateway disponibilizado pela Pharmanexo. h) fazer mais de um anúncio para o mesmo produto.</p>
    <p id="u59559-322">Estes tipos de comportamento poderão ser sancionados com o cancelamento do anúncio, ou com a suspensão da sua conta como Usuário do Pharmanexo, sem prejuízo das ações legais que possam ocorrer pela configuração de delitos ou contravenções ou os prejuízos civis que possam causar aos Usuários compradores, à Pharmanexo ou terceiros.</p>
    <p id="u59559-326">09 - Violação no sistema ou da base de dados</p>
    <p id="u59559-329">Não é permitida a utilização de nenhum dispositivo, software ou outro recurso que venha a interferir nas atividades e operações da Pharmanexo, bem como nos anúncios, descrições, contas ou seus bancos de dados.</p>
    <p id="u59559-332">Qualquer intromissão, tentativa ou atividade que viole ou contrarie as leis de direito de propriedade intelectual e/ou as proibições estipuladas nestes Termos e Condições Gerais de Uso, tornarão o responsável passível das ações legais pertinentes, bem como das sanções aqui previstas, sendo ainda responsável pelas indenizações por eventuais danos causados.</p>
    <p id="u59559-336">10 - Sanções</p>
    <p id="u59559-339">Sem prejuízo de outras medidas cabíveis, o Pharmanexo poderá advertir, suspender, temporária ou definitivamente, a conta de um Usuário, cancelar os seus anúncios ou aplicar uma sanção que impacte negativamente em sua reputação, a qualquer tempo, iniciando as ações legais cabíveis e/ou suspendendo a prestação de seus serviços se: a) o Usuário não cumprir qualquer dispositivo destes Termos e condições gerais de uso e demais políticas do Pharmanexo; b) se descumprir com seus deveres de Usuário; c) se praticar atos fraudulentos ou dolosos; d) se não puder ser verificada a identidade do Usuário ou se qualquer informação fornecida por ele estiver incorreta; e) se a Pharmanexo entender que os anúncios ou qualquer atitude do Usuário tenham causado algum dano a terceiros ou à própria Pharmanexo ou tenham a potencialidade de assim o fazer.</p>
    <p id="u59559-342">Nos casos suspensão da conta do usuário, todos os anúncios ativos e/ou ofertas realizadas serão automaticamente cancelados e a informação de que Usuário não pertencerá mais à comunidade será incluída ao lado do nome de Usuário.</p>
    <p id="u59559-345">O Pharmanexo reserva-se o direito de, a qualquer momento e a seu exclusivo critério, solicitar o envio de documentação pessoal e/ou exigir que um Usuário torne-se ‘Certificado’.</p>
    <p id="u59559-349">11 - Responsabilidades</p>
    <p id="u59559-352">O Pharmanexo se responsabiliza por eventuais danos causados aos seus Usuários por defeitos ou vícios relativos exclusivamente à prestação do seu serviço de hospedagem e veiculação de anúncios no site pharmanexo.com.br desde que a Pharmanexo tenha dado causa aos referidos defeitos ou vícios.</p>
    <p id="u59559-355">O Pharmanexo não se responsabiliza por vícios ou defeitos técnicos e/ou operacionais oriundos do sistema do Usuário ou de terceiros.</p>
    <p id="u59559-358">O Pharmanexo não é a proprietário dos produtos ou prestador dos serviços anunciados pelos Usuários nos Sites, não guarda a posse desses itens e não realiza as ofertas de venda, tampouco intervém na entrega dos produtos, salvo mediante a itermadiação para a contratação dos serviços de transporte disponibilizados pelo site.</p>
    <p id="u59559-361">&nbsp;A Pharmanexo não se responsabiliza, por conseguinte, pela existência, quantidade, qualidade, estado, integridade ou legitimidade dos produtos oferecidos, adquiridos ou alienados pelos Usuários, assim como pela capacidade para contratar dos Usuários ou pela veracidade dos dados pessoais por eles inseridos em seus cadastros.</p>
    <p id="u59559-364">A Pharmanexo não outorga garantia por vícios ocultos ou aparentes nas negociações entre os Usuários. Cada Usuário conhece e aceita ser o único responsável pelos produtos que anuncia ou pelas ofertas que realiza.</p>
    <p id="u59559-367">O Pharmanexo não será responsável pelo efetivo cumprimento das obrigações assumidas pelos Usuários.</p>
    <p id="u59559-370">O Usuário reconhece e aceita ao realizar negociações com outros Usuários ou terceiros o faz por sua conta e risco, reconhecendo a Pharmanexo como mero fornecedor de serviços de disponibilização de espaço virtual para anúncios de produtos e serviços ofertados por terceiros.</p>
    <p id="u59559-373">Em nenhum caso a Pharmanexo será responsável pelo lucro cessante ou por qualquer outro dano e/ou prejuízo que possa sofrer devido às negociações realizadas ou não realizadas por meio dos sites decorrentes da conduta de outros usuários.</p>
    <p id="u59559-376">A Pharmanexo recomenda que toda negociação seja realizada com cautela e bom senso.</p>
    <p id="u59559-379">Nos casos em que um ou mais Usuários ou algum terceiro inicie qualquer tipo de reclamação ou ação legal contra outro ou mais Usuários, todos e cada um dos Usuários envolvidos nas reclamações ou ações eximem de toda responsabilidade o Pharmanexo e os seus diretores, gerentes, empregados, agentes, operários, representantes.</p>
    <p id="u59559-383">12 - Alcance dos serviços</p>
    <p id="u59559-386">Estes Termos e Condições Gerais de Uso não geram nenhum contrato de sociedade, mandato, franquia ou relação de trabalho entre Pharmanexo e o Usuário.</p>
    <p id="u59559-389">O Usuário manifesta ciência de que a Pharmanexo não é parte de nenhuma negociação realizada entre Usuários, nem possui controle algum sobre a existência, qualidade, segurança ou legalidade dos produtos ou serviços anunciados pelos Usuários, sobre a veracidade ou exatidão dos anúncios elaborados pelos usuários e sobre a capacidade dos Usuários para negociar.</p>
    <p id="u59559-392">A Pharmanexo não pode assegurar o êxito de qualquer negociação realizada entre Usuários, limitando-se a verificar a identidade ou dos Dados Pessoais dos usuários realizados por seus respectivos cadastros.</p>
    <p id="u59559-396">13 - Falhas no sistema</p>
    <p id="u59559-399">A Pharmanexo não se responsabiliza por qualquer dano, prejuízo ou perda sofridos pelo Usuário em razão de falhas na internet, no sistema ou no servidor utilizado pelo usuário, decorrentes de condutas de terceiros, caso fortuito ou força maior.</p>
    <p id="u59559-402">A Pharmanexo também não será responsável por qualquer vírus que possa atacar o equipamento do usuário em decorrência do acesso, utilização ou navegação na internet ou como consequência da transferência de dados, arquivos, imagens, textos, vídeos ou áudio.</p>
    <p id="u59559-406">14 - Tarifas e faturamento</p>
    <p id="u59559-409">O cadastro no site Pharmanexo é gratuito. Todavia, será cobrada uma comissão sobre o êxito da venda, que somente será paga a Pharmanexo quando a negociação se concretizar.</p>
    <p id="u59559-412">O usuário concorda em pagar à Pharmanexo os valores correspondentes a qualquer serviço prestado pela Pharmanexo em que haja uma tarifa estabelecida.</p>
    <p id="u59559-415">A Pharmanexo se reserva o direito de modificar, aumentar ou excluir tarifas vigentes a qualquer momento, observado o estipulado na cláusula 04, ou durante promoções e outras formas transitórias de alteração dos preços praticados.</p>
    <p id="u59559-418">Tais alterações não vigorarão em relação às negociações e anúncios já iniciados na data em que tais alterações sejam publicadas. Para estes, os Termos e Condições Gerais de Uso valerão com a redação anterior.</p>
    <p id="u59559-421">A Pharmanexo se reserva o direito de tomar as medidas judiciais e extrajudiciais pertinentes para receber os valores devidos.</p>
    <p id="u59559-426"><span>15 - </span><span id="u59559-425">Propriedade Intelectual e links</span></p>
    <p id="u59559-429">O uso comercial da expressão "Pharmanexo" como marca, nome empresarial ou nome de domínio, bem como os conteúdos das telas relativas aos serviços da Pharmanexo assim como os programas, look and feel dos Sites, bancos de dados, redes, arquivos que permitem ao Usuário acessar e usar a sua Conta são propriedade da Pharmanexo e estão protegidos pelas leis e tratados internacionais de direito autoral, marcas, patentes, modelos e desenhos industriais.</p>
    <p id="u59559-432">O uso indevido e a reprodução total ou parcial dos referidos conteúdos são proibidos, salvo a autorização prévia e expressa por escrito da Pharmanexo.</p>
    <p id="u59559-434">O Usuário declara e garante que é titular, possui a devida autorização do(s) titular(es) de direito(s) de propriedade intelectual ou que, de outra forma, pode anunciar na Pharmanexo.</p>
    <p id="u59559-437">&nbsp;O Usuário assume total responsabilidade por todos os prejuízos, diretos e indiretos, inclusive indenizações, lucros cessantes, honorários advocatícios e demais encargos judiciais e extrajudiciais que a Pharmanexo seja obrigado a incorrer em virtude de ato ou omissão do Usuário.</p>
    <p id="u59559-440">Se o Pharmanexo receber alguma reclamação ou questionamento de terceiros (por exemplo, dos titulares de marca), a Pharmanexo poderá remover o seu anúncio e aplicar as sanções cabíveis.</p>
    <p id="u59559-444">16 - Indenização</p>
    <p id="u59559-447">O usuário indenizará a Pharmanexo, diretores, administradores, colaboradores, representantes e empregados por qualquer demanda promovida por outros Usuários ou terceiros decorrentes de suas atividades no Site ou por seu descumprimento dos Termos e condições gerais de uso e demais políticas do Pharmanexo, ou pela violação de qualquer lei ou direitos de terceiros, incluindo honorários de advogados.</p>
    <p id="u59559-451">17 - Legislação aplicável e Foro de eleição</p>
    <p id="u59559-454">Todos os itens destes Termos e condições gerais de uso são regidos pelas leis vigentes na República Federativa do Brasil. Para todos os assuntos referentes à interpretação, ao cumprimento ou qualquer outro questionamento relacionado a estes Termos e condições gerais de uso, as partes concordam em se submeter ao Foro da Cidade de Vitória-ES.</p>
    <p id="u59559-461">Todas as requisições, correspondências, notificações ou pedidos de informação deverão ser enviadas para o endereço do PHARMANEXO INTERMEDIAÇÃO DE NEGÓCIOS LTDA, situada na Av. Nossa Senhora dos Navegantes, n. 955, sala 719, Enseada do Suá, Vitória-ES, CEP n. 29.059-335.</p>
</div>

<?php if (isset($scripts)) echo $scripts; ?>
</body>
</html>
