<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$active_group = 'default';
$query_builder = TRUE;

$db['default'] = array(
	'dsn'	=> '',
	'hostname' => '10.101.70.5',
	'username' => 'adm_pharmanexo',
	'password' => 'Pisdnm238shdn',
	'database' => 'pharmanexo',
	'dbdriver' => 'mysqli',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => false,
	// 'db_debug' => (ENVIRONMENT !== 'production'),
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);

$db['teste_pharmanexo'] = array(
    'dsn'	=> '',
    'hostname' => '10.101.70.4',
    #'username' => 'pharmanexo',
    'username' => 'adm_pharmanexo',
    #'password' => '@PharmanexoNext',
    'password' => 'f}*=p8S1Bo4OnK',
    'database' => 'pharmanexo',
    'dbdriver' => 'mysqli',
    'dbprefix' => '',
    'pconnect' => FALSE,
    'db_debug' => false,
    // 'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => FALSE,
    'compress' => FALSE,
    'stricton' => FALSE,
    'failover' => array(),
    'save_queries' => TRUE
);

$db['sintese'] = array(
	'dsn'	=> '',
	'hostname' => '10.101.70.5',
	'username' => 'adm_pharmanexo',
	'password' => 'Pisdnm238shdn',
	'database' => 'cotacoes_sintese',
	'dbdriver' => 'mysqli',
	'dbprefix' => '',
	'pconnect' => FALSE,
	//'db_debug' => (ENVIRONMENT !== 'production'),
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);

$db['teste_sintese'] = array(
    'dsn'	=> '',
    'hostname' => '10.101.70.4',
    #'username' => 'pharmanexo',
    'username' => 'adm_pharmanexo',
    #'password' => '@PharmanexoNext',
    'password' => 'f}*=p8S1Bo4OnK',
    'database' => 'cotacoes_sintese',
    'dbdriver' => 'mysqli',
    'dbprefix' => '',
    'pconnect' => FALSE,
    //'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => FALSE,
    'compress' => FALSE,
    'stricton' => FALSE,
    'failover' => array(),
    'save_queries' => TRUE
);

$db['bionexo'] = array(
	'dsn'	=> '',
	'hostname' => '10.101.70.5',
	#'username' => 'pharmanexo',
	'username' => 'adm_pharmanexo',
	#'password' => '@PharmanexoNext',
	'password' => 'Pisdnm238shdn',
	'database' => 'cotacoes_bionexo',
	'dbdriver' => 'mysqli',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => (ENVIRONMENT !== 'production'),
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);

$db['apoio'] = array(
    'dsn'	=> '',
    'hostname' => '10.101.70.5',
    #'username' => 'pharmanexo',
    'username' => 'adm_pharmanexo',
    #'password' => '@PharmanexoNext',
    'password' => 'Pisdnm238shdn',
    'database' => 'cotacoes_apoio',
    'dbdriver' => 'mysqli',
    'dbprefix' => '',
    'pconnect' => FALSE,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => FALSE,
    'compress' => FALSE,
    'stricton' => FALSE,
    'failover' => array(),
    'save_queries' => TRUE
);

$db['teste_bionexo'] = array(
    'dsn'	=> '',
    'hostname' => '10.101.70.4',
    #'username' => 'pharmanexo',
    'username' => 'adm_pharmanexo',
    #'password' => '@PharmanexoNext',
    'password' => 'f}*=p8S1Bo4OnK',
    'database' => 'cotacoes_bionexo',
    'dbdriver' => 'mysqli',
    'dbprefix' => '',
    'pconnect' => FALSE,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => FALSE,
    'compress' => FALSE,
    'stricton' => FALSE,
    'failover' => array(),
    'save_queries' => TRUE
);

$db['apoio'] = array(
    'dsn'	=> '',
    'hostname' => '10.101.70.5',
    #'username' => 'pharmanexo',
    'username' => 'adm_pharmanexo',
    #'password' => '@PharmanexoNext',
    'password' => 'Pisdnm238shdn',
    'database' => 'cotacoes_apoio',
    'dbdriver' => 'mysqli',
    'dbprefix' => '',
    'pconnect' => FALSE,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => FALSE,
    'compress' => FALSE,
    'stricton' => FALSE,
    'failover' => array(),
    'save_queries' => TRUE
);

$db['mix'] = array(
	'dsn'	=> '',
	'hostname' => '10.101.70.5',
	#'username' => 'pharmanexo',
	'username' => 'adm_pharmanexo',
	#'password' => '@PharmanexoNext',
	'password' => 'Pisdnm238shdn',
	'database' => 'mix',
	'dbdriver' => 'mysqli',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => (ENVIRONMENT !== 'production'),
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);

$db['teste_mix'] = array(
	'dsn'	=> '',
	'hostname' => '10.101.70.4',
	#'username' => 'pharmanexo',
	'username' => 'adm_pharmanexo',
	#'password' => '@PharmanexoNext',
	'password' => 'f}*=p8S1Bo4OnK',
	'database' => 'mix',
	'dbdriver' => 'mysqli',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => (ENVIRONMENT !== 'production'),
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);
