on:
    push:
        branches: [main]
name: autodeploy digital ocean

jobs:
    deploy_code:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2

          - name: Setup SSH
            uses: MrSquaare/ssh-setup-action@v2
            with:
                host: '${{ secrets.SSH_HOST }}'
                private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: pull
            run: |
              cd /var/www/pharmanexo.com.br
              git pull
