on:
    push:
        branches: [main]
name: autodeploy digital ocean

jobs:
    deploy_code:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2

          - name: deploy arquivos
            uses: wlixcc/SFTP-Deploy-Action@v1.2.4
            with:
                username: ${{ secrets.SSH_USERNAME }}
                server: '${{ secrets.SSH_HOST }}'
                ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
                local_path: './*'
                remote_path: '/var/www/teste'
                sftpArgs: '-o ConnectTimeout=5'

