on:
    push:
        branches: [main]
name: autodeploy digital ocean

jobs:
    deploy_code:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout files
          - uses: actions/checkout@v2

          - name: Install doctl
          - uses: digitalocean/action-doctl@v2
            with:
                token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

          - name: SSH PULL
          - uses: appleboy/ssh-action@master
            with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                port: ${{ secrets.SSH_PORT }}
                script: |
                  cd ~/var/www/pharmanexo.com.br/
                  git fetch
                  git checkout main
                  git pull origin main
