on:
    push:
        branches: [main]
name: autodeploy digital ocean

jobs:
    deploy_code:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout files
            uses: actions/checkout@v2

          - name: Install doctl
            uses: digitalocean/action-doctl@v2
            with:
                token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
